models/Kelompok.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "kelompok".
 *
 * @property int $id
 * @property mixed $list
 * @property mixed $count
 * @property string $nama_kelompok [varchar(400)]
 */
class Kelompok extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'kelompok';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama_kelompok'], 'required'],
            [['nama_kelompok'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_kelompok' => 'Nama Kelompok',
        ];
    }

    public static function getList()
    {
        return ArrayHelper::map(self::find()->all(), 'id', 'nama_kelompok');
    }

    public function getCount()
    {
        return static::find()->count();
    }


    public static function findAllKelompok($kelompokId)
    {
        $query = Mahasiswa::find()->joinWith(['currentSemesterData'])->where(['semester_mahasiswa.kelompok_id' => $kelompokId])->orderBy('semester_mahasiswa.kelas_id');
        if (Yii::$app->user->identity->id_user_role === 2) {
            return $query
                ->andWhere(['semester_mahasiswa.kelompok_id' => Yii::$app->user->identity->semesterMahasiswa->kelompok_id, 'semester_mahasiswa.kelas_id' => Yii::$app->user->identity->semesterMahasiswa->kelas_id])
                ->all();
        }
        if (User::isKordinator()) {
            return $query
                ->andWhere(['semester_mahasiswa.kelas_id' => Yii::$app->user->identity->semesterMahasiswa->kelas_id])
                ->all();
        }

        return [];
    }
}

models/Revisi.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "revisi".
 *
 * @property int $id
 * @property string $judul
 * @property int $id_kelompok
 * @property int $id_proposal
 * @property string $file
 * @property string $deskripsi
 */
class Revisi extends \yii\db\ActiveRecord
{
    public $file_upload;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'revisi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['judul', 'id_kelompok', 'id_proposal', 'id_kelas', 'id_mhs', 'deskripsi'], 'required'],
            [['id_kelompok', 'id_kelas', 'id_mhs', 'id_proposal'], 'integer'],
            [['judul', 'deskripsi'], 'string', 'max' => 100],
            [['file_upload'], 'file', 'extensions'=>'docx, doc, pdf, xls, xlsx'],
            // [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'judul' => 'Judul Revisi',
            'id_kelompok' => 'Kelompok',
            'id_proposal' => 'Acuan Proposal',
            'id_kelas' => 'Kelas',
            'id_mhs' => 'Mahasiswa',
            'file_upload' => 'File',
            'deskripsi' => 'Deskripsi',
        ];
    }
    public function getCount()
    {
        return static::find()->count();
    }
    public function getKelompok()
    {
        return $this->hasOne(Kelompok::class, ['id' => 'id_kelompok']);
    }
    public function getProposal()
    {
        return $this->hasOne(Proposal::class, ['id' => 'id_proposal']);
    }
    public function getKelas()
    {
        return $this->hasOne(Kelas::class, ['id' => 'id_kelas']);
    }
    public function getMahasiswa()
    {
        return $this->hasOne(Mahasiswa::class, ['id' => 'id_mhs']);
    }

    public function getSemesterMahasiswa() {
        return $this->hasOne(SemesterMahasiswa::class, ['id'=> 'id_semester_mhs']);
    }
}

controllers/KelompokController.php
<?php

namespace app\controllers;

use app\models\Kelompok;
use app\models\KelompokSearch;
use app\models\SemesterMahasiswaSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * KelompokController implements the CRUD actions for Kelompok model.
 */
class KelompokController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kelompok models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->identity->id_user_role === 2) {
            return $this->redirect(['kelompok/view', 'id'=>Yii::$app->user->identity->semesterMahasiswa->kelompok_id]);
        }
        $searchModel = new KelompokSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Kelompok model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $searchModel = new SemesterMahasiswaSearch();
        $searchModel->kelompok_id=$id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Kelompok model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Kelompok();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Kelompok model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Kelompok model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Kelompok model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kelompok the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kelompok::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/kelompok/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use kartik\select2\Select2;
use app\models\Kelas;
use app\models\Mahasiswa;

/* @var $this yii\web\View */
/* @var $model app\models\Kelompok */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kelompok-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        
        <?= $form->field($model, 'nama_kelompok')->textInput(['maxlength' => true]) ?>
        
        </div>
        <div class="box-footer">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-flat']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>

views/kelompok/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\KelompokSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kelompok-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'logbook') ?>

    <?= $form->field($model, 'judul') ?>

    <?= $form->field($model, 'file') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kelompok/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Kelompok */

$this->title = 'Create Kelompok';
$this->params['breadcrumbs'][] = ['label' => 'Kelompoks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kelompok-create">

    <?= $this->render('_form', [
    'model' => $model,
    ]) ?>

</div>

views/kelompok/index.php
<?php

use app\models\User;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KelompokSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Kelompok';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kelompok-index box box-primary">
    <div class="box-header with-border">
        <?php if ((Yii::$app->user->identity->id_user_role === 1) || (Yii::$app->user->identity->id_user_role === 3) || (User::isKordinator())): ?>
            <?= Html::a('Create Kelompok', ['create'], ['class' => 'btn btn-info btn-flat']) ?>
        <?php endif ?>

        </div>

    <div class="box-body table-responsive no-padding">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                [
                    'class' => 'yii\grid\SerialColumn',
                    'header' => 'No',
                    'headerOptions' => ['style' => 'text-align:center'],
                    'contentOptions' => ['style' => 'text-align:center']
                ],
                'nama_kelompok',

                [
                    'template' => Yii::$app->user->identity->id_user_role === 2 ? '{view}' : '{view}{update}{delete}',
                    'class' => ActionColumn::class,
                    'contentOptions' => ['style' => 'text-align:center;width:80px']
                ],
            ],
        ]) ?>
    </div>
</div>

views/kelompok/random.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Kelompok;
use app\models\Kelas;
$this->title = 'Random Kelompok';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kelompok-index box box-primary">
	<div class="box-header with-border">	
		<div class="card" style="width: 18rem;">
			<div class="card-body">
				<h5 class="card-title">Kelas D3TI2B</h5>
			</div>
		</div>
		<?= Html::a('Generate', ['random-kelompok'], ['class' => 'btn btn-info btn-flat']) ?>
	</div>
</div>

views/kelompok/randomkelompok.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Kelompok;

$this->title = 'Hasil Random Kelompok';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kelompok-index box box-primary">
	<div class="box-header with-border">
		<div class="box box-info">
			<div class="box-header with-border">
				<h3 class="box-title">Hasil Random Kelompok</h3>
			</div>
			<div class="box-body">
				<table class="table table-bordered table-hover">
					<thead class="bg-blue">
						<tr>
							<th style="text-align: center; color: black; width: 50px;">No</th>
							<th style="text-align: center; color: black;">Nama Kelompok</th>
						</tr>
					</thead>
					<?php
					$mahasiswa = \app\models\Mahasiswa::find()->asArray()->all();
					$jml_kelompok = 2;
					$perkelompok  = count($mahasiswa) / $jml_kelompok;
					$mahasiswa_gaib[] = [
						'id' => 0,
						'nim' => '-',
						'nama' => '-',
						'id_kelas' => '-'
					];
					$kelompok = Kelompok::find()->all();
					foreach ($kelompok as $kel)
					{
						echo '<tr><th colspan="3" class="info"> ' .
						$kel->nama_kelompok .
						"</th></tr>";

						$i = 1;
						if (count($mahasiswa) % 2 !== 0) { 
							$mahasiswa = array_merge($mahasiswa,$mahasiswa_gaib);
						} 
						for ($i = 0; $i < $jml_kelompok; $i++)
						{
							$kel = array_rand($mahasiswa, round($perkelompok));
							$kelompok = 'Kelompok ' . ($i + 1);
							foreach ($kel as $key => $value) {
								// if ($kelompok->id_mahasiswa === $mahasiswa->id) {
								echo '<tr>
								<td style="text-align: center;">' . $i++ . '</td>
								<td>' . sprintf("insert %s %s", $kelompok, $mahasiswa[$value]['nama']) . '</td>
								</tr>';
							}
						}
					}
					?>
				</table>
			</div>
		</div>
	</div>
</div>

views/kelompok/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Kelompok */

$this->title = 'Update Kelompok: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Kelompoks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="kelompok-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/kelompok/view.php
<?php

use app\models\Kelompok;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Kelompok */

$this->title = $model->nama_kelompok;
$this->params['breadcrumbs'][] = ['label' => 'Kelompok', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="kelompok-view box box-primary">
        <div class="box-header">
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-flat']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger btn-flat',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        </div>
        <div class="box-body table-responsive no-padding">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    // 'id',
                    'nama_kelompok',
                ],
            ]) ?>
        </div>
    </div>

<?php if (Yii::$app->user->identity->id_user_role !== 1): ?>
    <div>&nbsp;</div>
    <div class="box box-primary">
        <div class="box-body">
            <div class="box-header">
                <h3 class="box-title">Daftar Mahasiswa</h3>
            </div>
            <div>&nbsp;</div>
            <table class="table">
                <tr>
                    <th>No</th>
                    <th>Nama</th>
                    <?php if (Yii::$app->user->identity->id_user_role === 3) : ?>
                        <th>Kelas</th>
                    <?php endif; ?>
                    <th></th>
                </tr>
                <?php $no = 1;
                foreach (Kelompok::findAllKelompok($model->id) as $mahasiswa): ?>
                    <tr>
                        <td><?= $no; ?></td>
                        <td><?= Html::a($mahasiswa->nama, ['mahasiswa/view', 'id' => $mahasiswa->id]); ?></td>
                        <?php if (Yii::$app->user->identity->id_user_role === 3) : ?>
                            <td><?= Html::a($mahasiswa->kelas->nama, ['kelas/view', 'id' => $mahasiswa->user->id]) ?></td>
                        <?php endif; ?>
                        <td>
                            <?= Html::a("<i class='fa fa-pencil'> Edit</i>", ["mahasiswa/update", "id" => $mahasiswa->id], ['class' => 'btn btn-primary']) ?>
                            &nbsp;
                            <?= Html::a("<i class='fa fa-trash'> Hapus</i>", ["mahasiswa/delete", "id" => $mahasiswa->id], ['class' => 'btn btn-danger', 'data-method' => 'post', 'data-confirm' => 'Yakin hapus data ini?']) ?>
                            &nbsp;
                        </td>
                    </tr>
                    <?php $no++; endforeach ?>
            </table>
        </div>
    </div>
<?php endif ?>


<?php if (Yii::$app->user->identity->id_user_role === 1): ?>
    <p>
        <?= Html::a('Tambah Mahasiswa', ['semester-mahasiswa/create', 'kelompokId'=>$model->id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'semesterCalender.semester',
            'kelompok.nama',
            'mahasiswa.nama',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php endif ?>